Refactor Tokenstat
omnivector-solutions/license-manager pull request #107
Opened 2022-01-25 02:48 UTC by julianaklulo

#### What
Refactor the Tokenstat module.
Each license server now has its own interface for connecting and parsing the server's ouput.
The logic for getting license's report was improved.
The tests were refactored as well.

#### Why
The old code was not scalable for adding support to more license servers.

`Task`: https://app.clickup.com/t/1hptz9b

2022-01-25 21:10 UTC, jamesbeedy commented
@julianaklulo will you make the first line of the docstring a proper sentence by ending with a period? Is there something we can put in the flake8 config to enforce this?

2022-01-25 21:52 UTC, dusktreader commented
> @julianaklulo will you make the first line of the docstring a proper sentence by ending with a period? Is there something we can put in the flake8 config to enforce this?

We could use fake8-docstrings: https://pypi.org/project/flake8-docstrings/

2022-01-25 23:58 UTC, dusktreader requested changes
Nice work! Made some comments for you. Let me know when it's ready for another look.

2022-01-25 23:58 UTC, dusktreader commented on agent/lm_agent/config.py
> +    LMUTIL_PATH: DirectoryPath = _DEFAULT_BIN_PATH
It strikes me that settings like this could easily be captured in the config rows in the database. We should not act on this now, but it may be something to consider for later.

2022-01-25 23:58 UTC, dusktreader commented on agent/lm_agent/tokenstat.py
> +    LicenseManagerNonSupportedServerTypeError,
These custom exception types should probably live in their own module like `lm_agent.exceptions`.

2022-01-25 23:58 UTC, dusktreader commented on agent/lm_agent/tokenstat.py
> +class LicenseServerInterface(metaclass=abc.ABCMeta):
There should be a docstring for this class.

2022-01-25 23:58 UTC, dusktreader commented on agent/lm_agent/tokenstat.py
> +        raise NotImplementedError
For a method decorated with `abstractclassmethod`, you do not need to explicitly raise `NotImplementedError`. You can just leave it at the docstring.

2022-01-25 23:58 UTC, dusktreader commented on agent/lm_agent/tokenstat.py
> +        raise NotImplementedError
See comment above.

2022-01-25 23:58 UTC, dusktreader commented on agent/lm_agent/tokenstat.py
> +        host_ports = [(server.split(":")[1], server.split(":")[2]) for server in self.license_servers]
We shouldn't need to call `split` twice here.

2022-01-25 23:58 UTC, dusktreader commented on agent/lm_agent/tokenstat.py
> +            )
```suggestion
            feature_cmd = f"{cmd} {feature}"
            proc = await asyncio.create_subprocess_shell(
                feature_cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.STDOUT
            )
```

2022-01-25 23:58 UTC, dusktreader commented on agent/lm_agent/tokenstat.py
> +        if not parsed_output["total"]:
Should we use `get()` here instead or can we trust that the parser will always return output with a "total" item?

```suggestion
        if not parsed_output.get("total"):
```

2022-01-25 23:58 UTC, dusktreader commented on agent/lm_agent/tokenstat.py
> +        if not parsed_output["total"]:
Should we also check for "uses" and make sure that the "total" sub-dict includes its own "used" and "total"?

2022-01-25 23:58 UTC, dusktreader commented on agent/lm_agent/tokenstat.py
> +        host_ports = [(server.split(":")[1], server.split(":")[2]) for server in self.license_servers]
See comment above about `split`.

2022-01-25 23:58 UTC, dusktreader commented on agent/lm_agent/tokenstat.py
> +        # run each command in the list, one at a time, until one succeds
Is this comment accurate? It seems like if one of the command fails we will raise an exception immediately.

2022-01-25 23:58 UTC, dusktreader commented on agent/lm_agent/tokenstat.py
> +        if not current_feature_item:
Should we also check `feature_booked_licenses` and `used_licenses`?

2022-01-25 23:58 UTC, dusktreader commented on agent/lm_agent/tokenstat.py
>          else:
As we add more license server types, it might be good to create a mapping (dict), attempt to fetch the appropriate type from it, and raise the exception if it cannot be found:

```suggestion
        server_type_map = dict(
            flexlm=FlexLMLicenseServer,
            rlm=RLMLicenseServer,
        )
        server_type = server_type_map.get(entry.license_server_type)
        if server_type is None:
            raise LicenseManagerNonSupportedServerTypeError()
        license_server_interface = server_type(entry.license_servers)
```

2022-01-26 20:49 UTC, julianaklulo commented on agent/lm_agent/tokenstat.py
> +    LicenseManagerNonSupportedServerTypeError,
Totally, I created the `exceptions` module and moved all the exceptions.

2022-01-26 20:54 UTC, julianaklulo commented on agent/lm_agent/tokenstat.py
> +class LicenseServerInterface(metaclass=abc.ABCMeta):
Addressed in latest commit.

2022-01-26 20:54 UTC, julianaklulo commented on agent/lm_agent/tokenstat.py
> +        raise NotImplementedError
Addressed in latest commit.

2022-01-26 20:54 UTC, julianaklulo commented on agent/lm_agent/tokenstat.py
> +        raise NotImplementedError
Addressed in latest commit.

2022-01-26 21:02 UTC, julianaklulo commented on agent/lm_agent/tokenstat.py
> +        host_ports = [(server.split(":")[1], server.split(":")[2]) for server in self.license_servers]
Yes. The license servers are defined like this: `flexlm:licserv0011.com:24200`, so I changed it to `server.split(":")[1:]` to get only the host and port we need and ignore the server type in the beginning. Thanks!

2022-01-26 21:05 UTC, julianaklulo commented on agent/lm_agent/tokenstat.py
> +            )
Addressed in latest commit.

2022-01-26 21:05 UTC, julianaklulo commented on agent/lm_agent/tokenstat.py
> +        host_ports = [(server.split(":")[1], server.split(":")[2]) for server in self.license_servers]
Addressed it.

2022-01-26 21:09 UTC, julianaklulo commented on agent/lm_agent/tokenstat.py
>          else:
Nice, I addressed in the latest commit. Now it looks much better!

2022-01-26 21:21 UTC, julianaklulo commented on agent/lm_agent/tokenstat.py
> +        # run each command in the list, one at a time, until one succeds
It should be, since we have to try all the hosts in the config row until one of them returns what we expect.
I added a continue statement to check the next host in case one of them fails. If they all fail, then we'll raise the exception.

2022-01-26 21:24 UTC, julianaklulo commented on agent/lm_agent/config.py
> +    LMUTIL_PATH: DirectoryPath = _DEFAULT_BIN_PATH
I agree. The problem I see with adding it to the config row would be if we have two different environments using the same backend. The location of the binary in each of them could be different. But it would be better than using env vars for this.

2022-01-26 21:32 UTC, julianaklulo commented on agent/lm_agent/tokenstat.py
> +        if not parsed_output["total"]:
The `flexlm` parser will always return the `total` and `uses`.
If nothing was matched in the output, the `total` will be `None` and the `uses` an empty list.
If the total is not None, then it will always have the `total` and `used` inside.

But I'll add the validations anyway, better play it safe.

2022-01-26 22:02 UTC, julianaklulo commented on agent/lm_agent/tokenstat.py
> +        if not current_feature_item:
The `feature_booked_licenses` can be an empty list (if no one is using the license in the license server), which makes `used_licenses` an empty list as well.

I'll simplify it to only `current_feature_item` and `used_licenses`, since they're the data we need for the LicenseReportItem, and also validate both.

2022-01-26 23:05 UTC, dusktreader commented on agent/lm_agent/config.py
> +    LMUTIL_PATH: DirectoryPath = _DEFAULT_BIN_PATH
Yes. We will have to be thinking about this for Q2.

2022-01-26 23:27 UTC, dusktreader approved these changes
Looks very good! Nice work.

2022-01-27 00:06 UTC, merged