Tucker/port legacy features to armada mvp
omnivector-solutions/license-manager pull request #110
Opened 2022-01-27 22:58 UTC by dusktreader

#### What
Ported changes from the main branch to armada-mvp

#### Why
There have been several changes applied to the main branch that haven't been ported to the armada-mvp branch. These have now been ported in preparation for a staging release of armada-mvp.

---

#### Peer Review
Please follow the upstream omnivector documentation concerning
[peer-review guidelines](https://github.com/omnivector-solutions/Documentation/blob/main/Contributing/pr_review_standards.md#peer-review).

2022-01-28 00:39 UTC, jamesbeedy approved these changes
👍

2022-01-28 19:28 UTC, julianaklulo requested changes

2022-01-28 19:28 UTC, julianaklulo commented on agent/lm_agent/backend_utils.py
> +class LicenseManagerEmptyReportError(Exception):
This should be in the `exceptions` module

2022-01-28 19:28 UTC, julianaklulo commented on agent/lm_agent/backend_utils.py
>      resp = await backend_client.get("/lm/version")
Is the k8s backend using the `lm` prefix in the routes?

2022-01-28 19:28 UTC, julianaklulo commented on agent/lm_agent/exceptions.py
> +class LicenseManagerAuthTokenError(Buzz):
Why only this exception uses `buzz`?

2022-01-28 19:28 UTC, julianaklulo commented on agent/lm_agent/reconciliation.py
> -    LicenseManagerBackendConnectionError,
This should be in the `exceptions` module

2022-01-28 19:28 UTC, julianaklulo commented on agent/lm_agent/reconciliation.py
> +        raise LicenseManagerEmptyReportError()
The reconcile() function was updated in the main branch to get the server type from the config row instead of hardcoding "flexlm"

2022-01-28 19:28 UTC, julianaklulo commented on agent/pyproject.toml
> +    "LM2_AGENT_RLMSTAT_BIN_PATH = ./tests/mock_tools",
I don't think we have these envs set in the main branch, why is it needed?

```suggestion
    "LM2_AGENT_LMUTIL_PATH = ./tests/mock_tools",
    "LM2_AGENT_RLMUTIL_PATH = ./tests/mock_tools",
```

2022-01-28 19:28 UTC, julianaklulo commented on agent/tests/conftest.py
> -    settings.BIN_PATH = MOCK_BIN_PATH
```
@fixture(autouse=True)
def backend_setting():
    """
    Force a specific host for the backend
    """
    with patch.multiple(
        settings,
        BACKEND_BASE_URL="http://backend",
        LMUTIL_PATH=MOCK_BIN_PATH,
        RLMUTIL_PATH=MOCK_BIN_PATH,
    ) as mck:
        yield mck
```

2022-01-28 23:07 UTC, dusktreader commented on agent/tests/conftest.py
> -    settings.BIN_PATH = MOCK_BIN_PATH
We don't need this any more, because the armada-mvp branch uses pytest-env to load these settings for tests from the pytest section in pyproject.toml

2022-01-29 00:48 UTC, dusktreader commented on agent/lm_agent/backend_utils.py
>      resp = await backend_client.get("/lm/version")
Yes. It's for the ingress controller so it can route traffic to the right API.

2022-01-29 00:51 UTC, dusktreader commented on agent/lm_agent/exceptions.py
> +class LicenseManagerAuthTokenError(Buzz):
I think just an issue of working out-of-sync. I made the others inherit from Buzz instead of re-implementing the Buzz specific logic used by this Exception.

2022-01-29 00:51 UTC, dusktreader commented on agent/lm_agent/reconciliation.py
> -    LicenseManagerBackendConnectionError,
It's being imported from there...

2022-01-29 00:56 UTC, dusktreader commented on agent/pyproject.toml
> +    "LM2_AGENT_RLMSTAT_BIN_PATH = ./tests/mock_tools",
This is pytest configuration. It sets the environment variables for pytest.

2022-01-29 01:07 UTC, dusktreader commented on agent/lm_agent/reconciliation.py
> +        raise LicenseManagerEmptyReportError()
Cherry picked the missing commit over.

2022-02-02 16:43 UTC, julianaklulo commented on agent/pyproject.toml
> +    "LM2_AGENT_RLMSTAT_BIN_PATH = ./tests/mock_tools",
The env vars for flexlm and rlm binaries were renamed, so I think they should match the new names here.

2022-02-02 17:39 UTC, julianaklulo approved these changes
Looks nice!

2022-02-02 17:43 UTC, merged