Remove License Server Interfaces from tokenstat module
omnivector-solutions/license-manager pull request #117
Opened 2022-02-10 22:08 UTC by julianaklulo

#### What
Remove License Server Interfaces from tokenstat, creating modules for each one.
Also add debugging logs to tokenstat.

#### Why
All the license servers were cluttered in tokenstat, making it difficult to add a new interface.

2022-02-12 01:24 UTC, dusktreader requested changes
Added some comments and suggestions for you. Nice work!

2022-02-12 01:24 UTC, dusktreader commented on agent/lm_agent/server_interfaces/flexlm.py
> +import typing
Add a module docstring, please.

2022-02-12 01:24 UTC, dusktreader commented on agent/lm_agent/server_interfaces/flexlm.py
> +            feature = product_feature.split(".")[1]
Instead of using direct indexing, you *could* do this as:
```suggestion
            (_, feature) = product_feature.split(".")
```

2022-02-12 01:24 UTC, dusktreader commented on agent/lm_agent/server_interfaces/flexlm.py
> +        ):
```suggestion
        if any([
            parsed_output.get("total") is None,
            parsed_output.get("uses") is None,
            parsed_output.get("total", {}).get("used") is None,
            parsed_output.get("total", {}).get("total") is None,
        ]):
```

2022-02-12 01:24 UTC, dusktreader commented on agent/lm_agent/server_interfaces/license_server_interface.py
> +    It is expected the license information to be parsed into an LicenseReportItem.
```suggestion
    Abstract base class for License Server interface.

    The logic for obtaining the data output from the License Server should be encapsulated in
    the ``get_output_from_server`` method.

    After obtaining the output, the parsing and manipulation of the data should be implemented in
    the ``get_report_item`` method.

    The license information should be parsed into a ``LicenseReportItem``.
```

2022-02-12 01:24 UTC, dusktreader commented on agent/lm_agent/server_interfaces/license_server_interface.py
> +        )
```suggestion
        return all([
            hasattr(subclass, "get_output_from_server"),
            callable(subclass.get_output_from_server),
            hasattr(subclass, "get_report_item"),
            callable(subclass.get_report_item),
        ]) or NotImplemented
```

2022-02-12 01:24 UTC, dusktreader commented on agent/lm_agent/server_interfaces/rlm.py
> +import typing
Please add a module docstring.

2022-02-12 01:24 UTC, dusktreader commented on agent/lm_agent/server_interfaces/rlm.py
> +                # `converge_super` | `converge_gui_polygonica` | `converge_...`
I think it would be good to move these comments into the method docstring and explain the two cases with examples.

2022-02-12 01:24 UTC, dusktreader commented on agent/lm_agent/server_interfaces/rlm.py
> +            elif "".join(feature_item["feature"].split("_")[1:]) == feature:
Should there maybe be an `else` clause here that throws an exception if both patterns fail?

2022-02-12 01:24 UTC, dusktreader commented on agent/lm_agent/server_interfaces/utils.py
> +import asyncio
Please add a module docstring.

2022-02-12 01:24 UTC, dusktreader commented on agent/lm_agent/tokenstat.py
> +    logger.debug("#### Getting reconciliation report ####")
Nice!

2022-02-12 01:24 UTC, dusktreader commented on agent/tests/server_interfaces/test_flexlm.py
> +from unittest import mock
Please add a module docstring.

2022-02-14 12:31 UTC, julianaklulo commented on agent/lm_agent/server_interfaces/flexlm.py
> +import typing
Addressed in latest commit.

2022-02-14 12:32 UTC, julianaklulo commented on agent/lm_agent/server_interfaces/flexlm.py
> +            feature = product_feature.split(".")[1]
Nice, thanks!

2022-02-14 12:33 UTC, julianaklulo commented on agent/lm_agent/server_interfaces/flexlm.py
> +        ):
Nice, thanks!

2022-02-14 13:05 UTC, julianaklulo commented on agent/lm_agent/server_interfaces/license_server_interface.py
> +    It is expected the license information to be parsed into an LicenseReportItem.
Addressed in latest commit.

2022-02-14 13:07 UTC, julianaklulo commented on agent/lm_agent/server_interfaces/license_server_interface.py
> +        )
Addressed in latest commit.

2022-02-14 13:08 UTC, julianaklulo commented on agent/lm_agent/server_interfaces/rlm.py
> +import typing
Addressed in latest commit.

2022-02-14 13:25 UTC, julianaklulo commented on agent/lm_agent/server_interfaces/rlm.py
> +            elif "".join(feature_item["feature"].split("_")[1:]) == feature:
I don't think so, since it will always have `0`, `1` or more underscores in the `feature` name.

2022-02-14 13:27 UTC, julianaklulo commented on agent/lm_agent/server_interfaces/rlm.py
> +            elif "".join(feature_item["feature"].split("_")[1:]) == feature:
Also, if the feature is not in the list, the method will return None and an exception will be raised by the validation in the `get_report_item` method.

2022-02-14 13:32 UTC, julianaklulo commented on agent/lm_agent/server_interfaces/rlm.py
> +                # `converge_super` | `converge_gui_polygonica` | `converge_...`
Sure, I added a more detailed explanation in the docstring.

2022-02-14 13:39 UTC, julianaklulo commented on agent/lm_agent/server_interfaces/utils.py
> +import asyncio
Addressed in latest commit.

2022-02-14 13:40 UTC, julianaklulo commented on agent/tests/server_interfaces/test_flexlm.py
> +from unittest import mock
Addressed in latest commit.

2022-02-14 17:21 UTC, dusktreader approved these changes

2022-02-14 18:53 UTC, merged