V1 additional dev david
omnivector-solutions/license-manager pull request #20
Opened 2021-05-18 00:40 UTC by djkresta

https://omnivector-solutions.monday.com/boards/1204470680/pulses/1299676711

These changes introduce enhanced license tracking in the slurmctld
prolog that enforce only tracking licenses that meet the protocol:
`<product>.<feature>@<license_server>:<num_tokens>`

* test that no licenses returned when correct protocol not used
* test that correct license count is returned when correct
protocol is used
* move call to scontrol and output parsing to cmd_utils.py
* enhance slurmctldProlog to only track licenses that match the
protocol

2021-05-18 12:21 UTC, zsinx6 requested changes

2021-05-18 12:21 UTC, zsinx6 commented on src/licensemanager2/test/agent/test_slurmctld_prolog.py
> +# from unittest.mock import patch
This line can be removed

2021-05-18 12:21 UTC, zsinx6 commented on src/licensemanager2/test/agent/test_slurmctld_prolog.py
> +        )
What you think about changing this to use the patch as a test function decorator? In that way you can avoid indentation and will be easier to read.
We are already using this here, for example: https://github.com/omnivector-solutions/jobbergate-api-fastapi/blob/dac55d996930e0dcc7c584842c5e9e857438e562/jobbergateapi2/tests/apps/job_scripts/test_routers.py#L104

2021-05-18 12:21 UTC, zsinx6 commented on src/licensemanager2/workload_managers/slurm/cmd_utils.py
> +        raise Exception(msg)
It is a good practice to create our own class as subclass of Exception with a good name and docstring, just raising Exception it bad for readability.

```python
class MyException(Exception):
"""This exception is used when..."""
```

2021-05-18 12:21 UTC, zsinx6 commented on tox.ini
> +    poetry run flake8 {posargs} --ignore=W292,D400,W605,W503 src/licensemanager2/ jawthorizer/
Why ignore the W292?

2021-05-18 12:26 UTC, zsinx6 commented
And about the PR title, it is good to be a brief summary about what have been changed, this one name says nothing about the PR for someone outside of the project.

2021-05-18 13:02 UTC, heitorPB commented on src/licensemanager2/workload_managers/slurm/slurmctld_prolog.py
> +    init_logging("slurmctld-prolog")
I'm not sure `uvicorn` will call the `init_logging` function this way. Normally we initialize the logging system in the beginning of the file.

2021-05-18 14:11 UTC, jamesbeedy commented
> And about the PR title, it is good to be a brief summary about what have been changed, this one name says nothing about the PR for someone outside of the project.

I agree with this, and would also like to see a link to the monday item that drives this work in the description when possible.

```
Fixes: https://<url-to-monday-item>
```

2021-05-18 18:07 UTC, djkresta commented on tox.ini
> +    poetry run flake8 {posargs} --ignore=W292,D400,W605,W503 src/licensemanager2/ jawthorizer/
Ignored because per James we don't want a newline at the end of our file.

2021-05-18 18:07 UTC, djkresta commented on src/licensemanager2/workload_managers/slurm/slurmctld_prolog.py
> +    init_logging("slurmctld-prolog")
We had to put them inside main so they wouldn't be run at import time, but since figured out a better solution: move the functions out of the prolog into cmd_utils.py

2021-05-18 18:13 UTC, djkresta commented on src/licensemanager2/test/agent/test_slurmctld_prolog.py
> +# from unittest.mock import patch
Sorry, I see you are talking about the commented out line.. removed.

2021-05-18 18:17 UTC, djkresta commented on src/licensemanager2/test/agent/test_slurmctld_prolog.py
> +        )
I am not quite clear on how you are setting up the return value in the example you linked. From examples I have constructed this:
```
@mock.patch("licensemanager2.workload_managers.slurm.slurmctld_prolog.get_licenses_for_job", return_value=scontrol_parsed_output_good)
async def test_get_required_licenses_for_job_good(slurm_job_id: str, scontrol_parsed_output_good: List[str]):
    """
    Do I return the correct licenses when the license format matches?
    """
    license_booking_request = await get_required_licenses_for_job(
        slurm_job_id
    )
    assert len(license_booking_request.bookings) == 3
```

but I get:
```
>       if license_array[0] != "(null)":
E       TypeError: 'function' object is not subscriptable

src/licensemanager2/workload_managers/slurm/slurmctld_prolog.py:62: TypeError
```

I see in your example you set the return value in the function using 
`boto3_client_mock.client.return_value = s3_client_mock` 
but I don't see how that connects with the decorator
`@mock.patch("jobbergateapi2.apps.job_scripts.routers.boto3")`

Because boto3_client_mock is passed into the function as an argument.

2021-05-18 18:22 UTC, zsinx6 commented on src/licensemanager2/test/agent/test_slurmctld_prolog.py
> +# from unittest.mock import patch
```suggestion
```

2021-05-18 20:11 UTC, zsinx6 approved these changes

2021-05-19 15:58 UTC, jamesbeedy commented on src/licensemanager2/workload_managers/slurm/slurmctld_prolog.py
> +    _force_reconciliation,
@djkresta make these functions public

2021-05-21 18:58 UTC, jamesbeedy commented
👍

2021-05-21 18:59 UTC, merged