ASP-2210 Added the atomic check-then-set booking insertion
omnivector-solutions/license-manager pull request #216
Opened 2023-04-11 22:14 UTC by dusktreader

Added logic to do an atomic check-then-set insertion of the new booking.

---

#### Peer Review
Please follow the upstream omnivector documentation concerning
[peer-review guidelines](https://github.com/omnivector-solutions/Documentation/blob/main/Contributing/pr_review_standards.md#peer-review).

2023-04-12 14:25 UTC, matheushent commented on backend/lm_backend/api/routes/bookings.py
> +        .join(Inventory, Feature.id == Inventory.feature_id)
I believe one `join` inside the `select_from` and then `where` makes it easier to read and understand

2023-04-12 14:43 UTC, matheushent requested changes
You made a very nice logic. I just have one point for discussion; beyond that, good work here.

2023-04-12 14:43 UTC, matheushent commented on backend/lm_backend/api/routes/bookings.py
> +            raise HTTPException(status_code=400, detail=f"Object could not be read: {e}")
this seems more like a server error than a client error

2023-04-12 16:39 UTC, julianaklulo requested changes
The formula to calculate if a booking can be made needs to take into consideration the `reserved`, which is the amount of licenses reserved for usage outside the cluster (in desktop environments, for example).
It was previously known as the limit feature, but that name was misleading.

2023-04-12 16:39 UTC, julianaklulo commented on backend/lm_backend/api/routes/bookings.py
> +        select(Feature.id)
```suggestion
        select(Feature.id, Feature.reserved)
```

2023-04-12 16:39 UTC, julianaklulo commented on backend/lm_backend/api/routes/bookings.py
> +            < func.max(Inventory.total)
```suggestion
            func.sum(Booking.quantity)
            + func.max(Inventory.used)
            + booking.quantity
            + func.max(Feature.reserved)
            <= func.max(Inventory.total)
```

2023-05-18 15:59 UTC, dusktreader commented
This was already merged in another PR.

2023-05-18 15:59 UTC, closed without merging