Add feature bulk update
omnivector-solutions/license-manager pull request #257
Opened 2023-08-23 21:12 UTC by julianaklulo

#### What
Add an endpoint to bulk update features.

#### Why
The agent was making `n` requests to update `n` features, with the new endpoint it's reduced to only one request.

`Task`: https://app.clickup.com/t/18022949/PENG-1613

---

#### Peer Review
Please follow the upstream omnivector documentation concerning
[peer-review guidelines](https://github.com/omnivector-solutions/Documentation/blob/main/Contributing/pr_review_standards.md#peer-review).

2023-08-24 18:51 UTC, dusktreader requested changes
Looks good, but I have a suggestion to speed it up even more.

2023-08-24 18:51 UTC, dusktreader commented on backend/lm_backend/api/routes/features.py
> +        feature_id = await find_feature_id_by_name_and_client_id(
This is still going to be inefficient because you're going to be doing a `select` query for each feature individually. To speed it up, you could make a method that gets all the features to update using a query like:

```sql
select *
from features
join configuration
where (feature.name, configuration.cluster_client_id) in values
   ('foo', 1),
   ('bar', 2)
```

in sqlalchemy this would look something like
```python
query = (
    select(Feature)
    .join(Configuration)
    .where(
        tuple_(
            Feature.name, 
            Configuration.cluster_client_id
        ).in_(
            [
                ("foo", 1),
                ("bar", 2),
            ]
        )
    )
)
```

2023-08-25 17:57 UTC, julianaklulo commented on backend/lm_backend/api/routes/features.py
> +        feature_id = await find_feature_id_by_name_and_client_id(
Thank you for the suggestion. I ended up creating a `Feature CRUD` for and added the `bulk_update` method there, using the query you wrote.
The approach is similar with what we did with the `Booking CRUD`, to have a query for creating a booking.

2023-08-25 20:48 UTC, dusktreader approved these changes

2023-08-28 12:16 UTC, merged