[PENG-1689] Convert docs to mkdocs
omnivector-solutions/license-manager pull request #267
Opened 2023-09-05 12:48 UTC by julianaklulo

#### What
Convert the documentation to use mkdocs instead of sphinx.
Also update READMEs and CHANGELOGs to use .md.

#### Why
To improve the usability of the documentation and decrease the complexibity of the documentation build process.

`Task`: https://app.clickup.com/t/18022949/PENG-1689

---

#### Peer Review
Please follow the upstream omnivector documentation concerning
[peer-review guidelines](https://github.com/omnivector-solutions/Documentation/blob/main/Contributing/pr_review_standards.md#peer-review).

2023-09-06 18:24 UTC, dusktreader requested changes
Very nice! Have some feedback for you.

2023-09-06 18:24 UTC, dusktreader commented on agent/README.md
> +<p align="center">
For the READMEs, it might be simpler to just do something similar to what I did for Armasec:
```
> An [Omnivector](https://www.omnivector.io/) initiative
>
> [![omnivector-logo](https://omnivector-public-assets.s3.us-west-2.amazonaws.com/branding/omnivector-logo-text-black-horz.png)](https://www.omnivector.io/)
```

I don't think links for reporting bugs or requesting features are necessary in the sub-project.

2023-09-06 18:24 UTC, dusktreader commented on agent/CHANGELOG.md
> +This file keeps track of all notable changes to ``license-manager-agent``.
Double back-ticks are not needed for markdown.

2023-09-06 18:24 UTC, dusktreader commented on agent/README.md
> +The ``License Manager Agent`` is responsible for keeping the local cluster license totals
Double back-ticks.

2023-09-06 18:24 UTC, dusktreader commented on backend/README.md
> +<br />
See above comment.

2023-09-06 18:24 UTC, dusktreader commented on backend/README.md
> +The ``License Manager API`` is responsible for managing license configurations, storing license usage and handling booking requests. The API is used by the License Manager Agent to centralize the dat
Double back-ticks.

2023-09-06 18:24 UTC, dusktreader commented on docs/src/architecture.md
> +The ``License Manager Agent`` is responsible for keeping the local cluster license totals
No double back-ticks needed!

2023-09-06 18:24 UTC, dusktreader commented on lm-cli/README.md
> +<p align="center">
See comments on other READMEs

2023-09-07 14:38 UTC, julianaklulo commented on agent/README.md
> +<p align="center">
I removed it from the subprojects and left only in the repo README.

2023-10-10 15:44 UTC, dusktreader approved these changes

2023-10-10 15:56 UTC, merged