[ASP-4668] Split License Manager Simulator into two subprojects
omnivector-solutions/license-manager pull request #376
Opened 2024-08-08 17:20 UTC by julianaklulo

#### What
Split the License Manager Simulator into two subprojects:
* lm-simulator: includes the fake binaries, templates and job application example
* lm-simulator-api: includes only the REST API used to populate the templates

#### Why
To best way to install the License Manager Simulator is by creating a Python package to distribute the scripts when installing the package. To do so we don't need the API to come bundled with the scripts, so splitting the project decouples both packages.

`Task`: https://jira.scania.com/browse/ASP-4668

---

#### Peer Review
Please follow the upstream omnivector documentation concerning
[peer-review guidelines](https://github.com/omnivector-solutions/Documentation/blob/main/Contributing/pr_review_standards.md#peer-review).

2024-08-14 20:14 UTC, dusktreader requested changes

2024-08-14 20:14 UTC, dusktreader commented on .github/workflows/publish_on_tag.yaml
> +      matrix: { sub_project: ['lm-agent', 'lm-api', 'lm-cli', lm-simulator', 'lm-simulator-api'] }
Missing a quote here on `lm-simulator`

2024-08-15 18:27 UTC, julianaklulo commented on .github/workflows/publish_on_tag.yaml
> +      matrix: { sub_project: ['lm-agent', 'lm-api', 'lm-cli', lm-simulator', 'lm-simulator-api'] }
Nice catch, I fixed it!

2024-08-19 17:36 UTC, dusktreader approved these changes

2024-08-19 20:06 UTC, merged