Create functions to delete booking using grace_time
omnivector-solutions/license-manager pull request #42
Opened 2021-08-05 21:15 UTC by zsinx6

#### What
Delete booking in reconcile if the running time is greater than the grace_time.

#### Why
We need to remove the bookings after the job is over its grace_time.

`Task`: https://omnivector-solutions.monday.com/boards/1204470680/pulses/1456711228

2021-08-11 17:59 UTC, jamesbeedy commented on src/licensemanager2/workload_managers/slurm/cmd_utils.py
> +        f"{SQUEUE_PATH} --noheader --format='%A|%M|%T'",
can we use `shlex.quote()` here?

2021-08-11 18:13 UTC, dusktreader requested changes

2021-08-11 18:13 UTC, dusktreader commented on src/licensemanager2/agent/reconciliation.py
> +    if response.status_code != 200:
It's probably best to use constants for error codes. 200 is pretty trivial, but when it comes to handling stuff in the 400 range I like to have the human-readable constants:

httpx.codes.OK (200)
httpx.codes.BAD_REQUEST (400)
httpx.codes.FORBIDDEN (403)
etc...

2021-08-11 18:13 UTC, dusktreader commented on src/licensemanager2/agent/reconciliation.py
> +    grace_times = {}
We could build this with a dict comprehension:

```python
grace_times = {c["id"]: c["grace_time"] for c in configs}
```

2021-08-11 18:13 UTC, dusktreader commented on src/licensemanager2/agent/reconciliation.py
> +        job_id_greatest_grace_time[job_id] = 0
I don't think we need to pre-seed this with 0s. Instead, in the loop below (`for job_id in job_id_greatest_grace_time.keys()`) we can instead just loop over job in sque_running_jobs again

2021-08-11 18:13 UTC, dusktreader commented on src/licensemanager2/agent/reconciliation.py
> +    for job in squeue_running_jobs:
This loop and the previous one could be collapsed together, couldn't they?

2021-08-11 18:13 UTC, dusktreader commented on src/licensemanager2/test/agent/test_reconciliation.py
> +        1: 100,
I think we should have more values here to test edge-cases more thoroughly

2021-08-11 18:13 UTC, dusktreader commented on src/licensemanager2/test/agent/test_reconciliation.py
> +    remove_booked_for_job_id_mock.assert_awaited_once()
should this check the parameters passed?

2021-08-11 18:13 UTC, dusktreader commented on src/licensemanager2/workload_managers/slurm/cmd_utils.py
> +def squeue_parser(squeue_formatted_output) -> List:
I wonder if it would be useful to create a pydantic model for what job items contain. I think it might help the code be more self-documenting and the access/usage in the gracetime cleanup methods might be a bit smoother.

2021-08-11 19:09 UTC, zsinx6 commented on src/licensemanager2/workload_managers/slurm/cmd_utils.py
> +        f"{SQUEUE_PATH} --noheader --format='%A|%M|%T'",
Yes, but since the entire string is something we provide ourselves, does it make sense to use?

2021-08-11 19:35 UTC, zsinx6 commented on src/licensemanager2/test/agent/test_reconciliation.py
> +        1: 100,
Do you have any suggestion?

2021-08-11 19:45 UTC, zsinx6 commented on src/licensemanager2/workload_managers/slurm/cmd_utils.py
> +def squeue_parser(squeue_formatted_output) -> List:
I don't think it will help much, the result is already very simple, just a dict with 3 keys

2021-08-12 14:20 UTC, jamesbeedy commented on src/licensemanager2/workload_managers/slurm/cmd_utils.py
> +        f"{SQUEUE_PATH} --noheader --format='%A|%M|%T'",
See [here](https://docs.python.org/3/library/shlex.html#shlex.quote), templating the variable into the command, even in our use case exposes the security hole.

2021-08-12 14:21 UTC, jamesbeedy commented on src/licensemanager2/workload_managers/slurm/cmd_utils.py
> +        f"{SQUEUE_PATH} --noheader --format='%A|%M|%T'",
We have tried to make it a convention to use this throughout license-manager.

2021-08-12 17:27 UTC, jamesbeedy commented
👍

2021-08-12 20:56 UTC, dusktreader approved these changes

2021-08-12 20:56 UTC, jamesbeedy commented
👍

2021-08-12 20:56 UTC, merged