In use cleanup
omnivector-solutions/license-manager pull request #51
Opened 2021-08-18 11:55 UTC by zsinx6

#### What
Implement in use cleanup.

#### Why
We need to clean the in use licenses from the booking table.

`Task`: https://omnivector-solutions.monday.com/boards/1204470680/pulses/1456713032

2021-08-18 21:36 UTC, dusktreader requested changes

2021-08-18 21:36 UTC, dusktreader commented on agent/lm_agent/main.py
> +app: Any = FastAPI()
Shouldn't the type for `app` be `FastAPI`?

2021-08-18 21:36 UTC, dusktreader commented on agent/lm_agent/main.py
> +    app = SentryAsgiMiddleware(app)
I think the idiomatic FastAPI way to do this is:

```python
app.add_middleware(SentryAsgiMiddleware)
```

see: https://fastapi.tiangolo.com/advanced/middleware/#adding-asgi-middlewares

2021-08-18 21:36 UTC, dusktreader commented on agent/lm_agent/reconciliation.py
> +    logger.debug(f"response from delete: {response.__dict__}")
do we want to leave this in, or was this only for debugging?

2021-08-18 21:36 UTC, dusktreader commented on agent/lm_agent/reconciliation.py
> +    greatest_grace_time = -1
Should an exception be raised if, after traversing the booking rows, greatest_grase_time is still -1?

2021-08-18 21:36 UTC, dusktreader commented on agent/lm_agent/reconciliation.py
> +            if grace_times[config_id_for_grace_times] > greatest_grace_time:
you could replace these two lines with:
```python
greatest_grace_time = max(greatest_gracetime, grace_times[config_id_for_grace_times])
```
I think it might read nicely this way

2021-08-18 21:36 UTC, dusktreader commented on agent/lm_agent/reconciliation.py
> +    for job in squeue_result:
I think this logic could be reduced with a list comprehension (or filter() ):
```python
return [j for j in squeue_result if j["state"] == "RUNNING"]
```

2021-08-18 21:36 UTC, dusktreader commented on agent/lm_agent/reconciliation.py
> +    booking_rows_for_running_jobs = await asyncio.gather(*get_booked_call, return_exceptions=True)
How does the loop below handle gathered exception results?

2021-08-18 21:36 UTC, dusktreader commented on agent/lm_agent/workload_managers/slurm/cmd_utils.py
> +async def get_required_licenses_for_job(slurm_job_id: str, user_name: str, lead_host: str) -> Any:
Seems like the return type should be LicenseBookingRequest

2021-08-18 21:36 UTC, dusktreader commented on agent/lm_agent/workload_managers/slurm/cmd_utils.py
> +        return []
I don't understand why we would return an empty list here. Should it be None instead since a successful lookup returns a single instance of LicenseBookingRequest?

2021-08-18 21:36 UTC, dusktreader commented on agent/lm_agent/workload_managers/slurm/cmd_utils.py
> +                product_feature, license_server_tokens = requested_license.split("@")
Seems like we should be using the match groups for this instead of using `split()`.

Also, I would like to see this logic split out into a function with a set of unit tests that bash on the edge-cases a little bit

2021-08-18 21:36 UTC, dusktreader commented on backend/lm_backend/api/license.py
> +            .where(booking_table.c.lead_host == used_license["lead_host"])
Nitpicky comment: you can send all three expressions to a single where:

```python
booking_table.select().where(
    booking_table.c.lead_host == used_kicense["lead_host"],
    booking_table.c.user_name == used_kicense["user_name"],
    booking_table.c.booked == used_kicense["booked"],
)
```

2021-08-18 21:36 UTC, dusktreader commented on backend/lm_backend/api/license.py
> +    for item in fetched:
maybe collapse into list comprehension

2021-08-19 12:11 UTC, zsinx6 commented on agent/lm_agent/reconciliation.py
> +    logger.debug(f"response from delete: {response.__dict__}")
To leave it in

2021-08-19 14:17 UTC, jamesbeedy commented on agent/lm_agent/reconciliation.py
> +    logger.debug(f"response from delete: {response.__dict__}")
> do we want to leave this in, or was this only for debugging?

Both :)

2021-08-19 14:32 UTC, zsinx6 commented on agent/lm_agent/reconciliation.py
> +    greatest_grace_time = -1
I'm not sure which way is better for readability, don't know if handling the exception in the outside function is good as well

2021-08-19 14:39 UTC, zsinx6 commented on agent/lm_agent/reconciliation.py
> +    booking_rows_for_running_jobs = await asyncio.gather(*get_booked_call, return_exceptions=True)
It doesn't, will remove this flag, if any exception happens in this method, something is wrong and should to go sentry

2021-08-19 14:47 UTC, zsinx6 commented on backend/lm_backend/api/license.py
> +            .where(booking_table.c.lead_host == used_license["lead_host"])
Actually not really:
`TypeError: where() takes 2 positional arguments but 5 were given`, and also I think this is more easy to add things if easy "operation" (e.g. where) is in its own line

2021-08-19 21:05 UTC, dusktreader commented on agent/lm_agent/reconciliation.py
> +    greatest_grace_time = -1
Fair enough. I think usage will illuminate if we need an exception or not. This is good for now

2021-08-19 21:07 UTC, dusktreader commented on backend/lm_backend/api/license.py
> +            .where(booking_table.c.lead_host == used_license["lead_host"])
Welp. The databases docs say they support sqlalchemy API, but it doesn't seem to line up. Good the way it was!

2021-08-19 21:32 UTC, dusktreader requested changes
A few more comments for you

2021-08-19 21:32 UTC, dusktreader commented on backend/tests/api/test_license.py
> +    booking_rows = [BookingRow.parse_obj(x) for x in await database.fetch_all(booking_table.select())]
I don't think we need to parse the response in this test. We could just count the results

2021-08-19 21:32 UTC, dusktreader commented on backend/tests/api/test_license.py
> +    booking_rows = [BookingRow.parse_obj(x) for x in await database.fetch_all(booking_table.select())]
Same here. No need to parse

2021-08-19 21:32 UTC, dusktreader commented on backend/tests/api/test_license.py
> +    booking_rows = [BookingRow.parse_obj(x) for x in await database.fetch_all(booking_table.select())]
extra parse()

2021-08-19 21:59 UTC, jamesbeedy commented on agent/lm_agent/workload_managers/slurm/slurmctld_epilog.py
> +    license_booking_request = await get_required_licenses_for_job(job_id, user_name, lead_host)
Since we don't use `user_name` or `grace_time` in the `get_required_licenses_for_job()` function, possibly it is better to have it return a list of `LicenseBooking` instead of a `LicenseBookingRequest`?

2021-08-19 22:00 UTC, jamesbeedy commented on backend/lm_backend/api/license.py
> +            .where(booking_table.c.product_feature == license.product_feature)
👍

2021-08-19 22:05 UTC, jamesbeedy requested changes
Looking good! Resolve the comments and then I'll be +1.

2021-08-23 16:26 UTC, matheushent commented on agent/lm_agent/reconciliation.py
> +    response = await async_client().delete(f"/api/v1/booking/book/{job_id}")
shouldn't this be a redirection instead of a direct call?

2021-08-23 16:30 UTC, matheushent commented on agent/lm_agent/reconciliation.py
> +    response = await async_client().get(f"/api/v1/booking/job/{job_id}")
same comment about redirection

2021-08-23 16:36 UTC, zsinx6 commented on agent/lm_agent/reconciliation.py
> +    response = await async_client().delete(f"/api/v1/booking/book/{job_id}")
Can you explain more?

2021-08-23 16:37 UTC, matheushent commented on agent/lm_agent/workload_managers/slurm/cmd_utils.py
>          resp = client.get(f"{settings.AGENT_BASE_URL}/api/v1/license/all", headers=LM2_AGENT_HEADERS)
same comment about redirection

2021-08-23 16:39 UTC, matheushent commented on agent/lm_agent/reconciliation.py
> +    response = await async_client().delete(f"/api/v1/booking/book/{job_id}")
I'd like to see `RedirectResponse` from starlette being used here. It seems more coherent to me. Thoughts?

2021-08-23 16:40 UTC, matheushent commented on agent/lm_agent/reconciliation.py
> +    response = await async_client().delete(f"/api/v1/booking/book/{job_id}")
It seems to me that doing the current way the API iteself increases its traffic. It seems inefficient some way

2021-08-23 16:41 UTC, zsinx6 commented on agent/lm_agent/workload_managers/slurm/slurmctld_epilog.py
> +    license_booking_request = await get_required_licenses_for_job(job_id, user_name, lead_host)
Actually we build the entire license_booking_request using the `user_name` and `lead_host`. If we build the object outside the function it will only move the logic around, I don't see the point of modify this

2021-08-23 16:42 UTC, matheushent commented on agent/lm_agent/reconciliation.py
> +    response = await async_client().delete(f"/api/v1/booking/book/{job_id}")
> Can you explain more?

The current way the API calls itself, which I think may be inefficient since the API would be increasing its own traffic. Perhaps we could improve it using `RedirectResponse` from starlette

2021-08-23 16:43 UTC, zsinx6 commented on agent/lm_agent/reconciliation.py
> +    response = await async_client().delete(f"/api/v1/booking/book/{job_id}")
But why redirect? We need to actually make a call to that endpoint

2021-08-23 16:44 UTC, matheushent commented on agent/lm_agent/reconciliation.py
> +    response = await async_client().delete(f"/api/v1/booking/book/{job_id}")
yep, but internally it doesn't necessary mean a call but a redirection. I wonder the efficiency of this. We can improve that

2021-08-23 16:44 UTC, matheushent commented on agent/lm_agent/reconciliation.py
> +    response = await async_client().delete(f"/api/v1/booking/book/{job_id}")
redirection instead of direct call means less network traffic

2021-08-23 16:44 UTC, zsinx6 commented on agent/lm_agent/reconciliation.py
> +    response = await async_client().delete(f"/api/v1/booking/book/{job_id}")
No, the api will not call itself, it is going to call the backend

2021-08-23 16:45 UTC, zsinx6 commented on agent/lm_agent/reconciliation.py
> +    response = await async_client().delete(f"/api/v1/booking/book/{job_id}")
Take a look at the async_client: https://github.com/omnivector-solutions/license-manager/blob/75829ed873bc0f3c1c66902da5a8ba08e7ccc326/agent/lm_agent/forward.py#L25

2021-08-23 16:49 UTC, matheushent commented on agent/lm_agent/reconciliation.py
> +    response = await async_client().delete(f"/api/v1/booking/book/{job_id}")
I still think this can be improved to a internal redirection instead of a local network call. But anyway, I'd like more thoughts on that

2021-08-23 16:50 UTC, matheushent commented on agent/lm_agent/reconciliation.py
> +    response = await async_client().delete(f"/api/v1/booking/book/{job_id}")
I couldn't see in starlette's code whether this is done the same way

2021-08-23 16:51 UTC, zsinx6 commented on agent/lm_agent/reconciliation.py
> +    response = await async_client().delete(f"/api/v1/booking/book/{job_id}")
The backend is in AWS, it must be a outside call

2021-08-23 16:54 UTC, matheushent commented on agent/lm_agent/reconciliation.py
> +    response = await async_client().delete(f"/api/v1/booking/book/{job_id}")
Perhaps I meant confusedly. I meant not returning the redirect response but using the RedirectResponse just to call the API internally

2021-08-23 17:01 UTC, matheushent commented on agent/lm_agent/reconciliation.py
> +    response = await async_client().delete(f"/api/v1/booking/book/{job_id}")
oh now I see, it doesn't make sense what I'm saying. Just ignore it

2021-08-23 20:50 UTC, dusktreader approved these changes
Nice work!

2021-08-24 14:09 UTC, jamesbeedy commented on agent/lm_agent/workload_managers/slurm/slurmctld_epilog.py
> +    license_booking_request = await get_required_licenses_for_job(job_id, user_name, lead_host)
I guess I wasn't very clear ... my thoughts are basically that if we don't need the `LicenseBookingRequest` object, we just need the bookings, then why pass this information around and create this `LicenseBookingRequest` when we can just change the return type of the function and have it only return a list of bookings?

2021-08-24 15:22 UTC, jamesbeedy approved these changes
Thank you for resolving this! 👍

2021-08-24 16:52 UTC, merged