Booking account
omnivector-solutions/license-manager pull request #59
Opened 2021-09-15 19:32 UTC by zsinx6

#### What
Add booking accounting.
Make sure to handle the response correctly and with logs.
Small fixes in .gitignore and Makefile.
Removed dead code.

#### Why
We need to account for the current number of booking before creating a new one.

2021-09-16 12:11 UTC, zsinx6 commented on agent/Makefile
> +SHELL := /bin/bash
For some reason I had problems without this, and it is already there for the backend part. But I'm not sure why it interferes with poetry

2021-09-16 17:16 UTC, heitorPB commented on agent/Makefile
> +SHELL := /bin/bash
Poetry is not POSIX compliant, so you have to force to use Bash instead.

2021-09-16 21:51 UTC, dusktreader requested changes

2021-09-16 21:51 UTC, dusktreader commented on agent/lm_agent/workload_managers/slurm/slurmctld_prolog.py
> +            logger.debug("Booking request unsuccessful.")
Should this be `logger.error(...)`?

2021-09-16 21:51 UTC, dusktreader commented on agent/lm_agent/workload_managers/slurm/slurmctld_prolog.py
> +        if booking_request:
I think you could restructure this without an else as:
```python
if not booking_request:
    logger.error(...)
    sys.exit(1)
logger.debug(success_message)
```

I'm not sure that the explicit sys.exit(0) is necessary. Doesn't python use a 0 by default when a process completes normally?

2021-09-16 21:51 UTC, dusktreader commented on backend/lm_backend/api/booking.py
> +    """For each product_feature in the booking.features, check if the total of in_use_total + new_booked
The language here is a little bit confusing. Maybe "check if the total available is greater than the sum of in_use_total and new_booked."

2021-09-16 21:51 UTC, dusktreader commented on backend/lm_backend/api/booking.py
> +            detail=(f"Couldn't book {booking.job_id}, not enough licenses available."),
I don't think the parens are necessary.

2021-09-17 12:43 UTC, zsinx6 commented on agent/lm_agent/workload_managers/slurm/slurmctld_prolog.py
> +        if booking_request:
I think it is good to be as explicit as possible there

2021-09-17 12:47 UTC, zsinx6 commented on backend/lm_backend/api/booking.py
> +    """For each product_feature in the booking.features, check if the total of in_use_total + new_booked
Can you check again now?

2021-09-17 12:52 UTC, jamesbeedy commented on backend/lm_backend/api/booking.py
> +    for product_feature in booking.features:
The use of product_feature and feature don’t match what the variable actually represents, this makes reading and understanding the code less clear. Can we clean up the terminology so that, for example,  a product_feature is a product_feature and a feature is a feature?

2021-09-17 12:53 UTC, jamesbeedy commented on backend/lm_backend/api/booking.py
> +        for license in product_feature_licenses:
This too

2021-09-21 20:16 UTC, dusktreader approved these changes
Looks good!

2021-09-22 04:46 UTC, jamesbeedy commented
👍 from me. Possibly we wait until after the demo tomorrow to merge this, incase there are any additional adds we may need to make.

2021-09-22 16:54 UTC, merged