Clean bookings
omnivector-solutions/license-manager pull request #64
Opened 2021-09-30 13:11 UTC by zsinx6

#### What
Remove not used remaining bookings.

#### Why
To avoid unused bookings.

2021-10-04 21:50 UTC, dusktreader requested changes
Nice work! Left a few comments for you.

2021-10-04 21:50 UTC, dusktreader commented on agent/lm_agent/backend_utils.py
> +async def get_bookings_from_backend(cluster_name: str = None) -> List[BackendBookingRow]:
Seems like this would cause a Mypy error. Probably need to add Optional:

```suggestion
async def get_bookings_from_backend(cluster_name: Optional[str] = None) -> List[BackendBookingRow]:
```

2021-10-04 21:50 UTC, dusktreader commented on agent/lm_agent/reconciliation.py
> +            delete_booking_call.append(remove_booked_for_job_id(job_id))
Seems like we could combine the two if clauses:

```suggestion
        if job_id in jobs_not_running or job_id not in all_jobs_squeue:
            delete_booking_call.append(remove_booked_for_job_id(job_id))
```

2021-10-04 21:50 UTC, dusktreader commented on agent/lm_agent/reconciliation.py
> +        if new_quantity > license_total:
Maybe use `max()` and `min()` here instead to do a range clamp?
```
new_quantity = min(new_quantity, license_total)
new_quantity = max(new_quantity, 0)
```

You could combine to one line as well for compactness, but it hurts readability.

Just for fun, I saw this on Stack Overflow (should not use because it's confusing, but I thought it was amusing):
```python
new_quantity = sorted((0, new_quantity, license_total))[1]
```

2021-10-04 21:50 UTC, dusktreader commented on agent/lm_agent/reconciliation.py
> +            logger.info("Slurmdbd update unsuccessful.")
should this be `logger.error` or `logger.warn`?

2021-10-04 21:50 UTC, dusktreader commented on agent/lm_agent/workload_managers/slurm/cmd_utils.py
> +    logger.debug(f"{' '.join(cmd)}")
Seems like you could do the log after the `shlex.join()` so you don't have to do this separately.

2021-10-04 21:50 UTC, dusktreader commented on agent/lm_agent/workload_managers/slurm/cmd_utils.py
> +        "-nP",
for readability, it might be good to  use the full long-options here.

2021-10-04 21:50 UTC, dusktreader commented on agent/lm_agent/workload_managers/slurm/slurmctld_epilog.py
> +            logger.debug(f"Booking for job id: {job_id} not removed.")
Should this be warn or error?

2021-10-07 13:43 UTC, zsinx6 commented on agent/lm_agent/workload_managers/slurm/slurmctld_epilog.py
> +            logger.debug(f"Booking for job id: {job_id} not removed.")
No, this is just for debug

2021-10-07 13:44 UTC, zsinx6 commented on agent/lm_agent/workload_managers/slurm/cmd_utils.py
> +    logger.debug(f"{' '.join(cmd)}")
It is just a debug log, so I think it doesn't matter much

2021-10-07 13:44 UTC, zsinx6 commented on agent/lm_agent/reconciliation.py
> +            logger.info("Slurmdbd update unsuccessful.")
I think we just want to inform this in the logs, so info seems correct

2021-10-07 13:45 UTC, zsinx6 commented on agent/lm_agent/reconciliation.py
> +        if new_quantity > license_total:
We will change this in the next PR

2021-10-07 15:53 UTC, dusktreader approved these changes

2021-10-07 16:49 UTC, merged