Add minimum_licenses in the config table
omnivector-solutions/license-manager pull request #65
Opened 2021-10-11 14:30 UTC by zsinx6

#### What
Add minimum_licenses in the config table in the features column.

#### Why
To be able to configure the minimum value using the database.

2021-10-11 18:05 UTC, dusktreader requested changes

2021-10-11 18:05 UTC, dusktreader commented on agent/lm_agent/reconciliation.py
> +                minimum_value = config.features[product_feature.split(".")[1]]
should there be a `break` here?

2021-10-11 18:05 UTC, dusktreader commented on backend/lm_backend/api/config.py
> +async def get_config_id_for_product_features(product_feature: str) -> Union[int, None]:
Need a docstring here.

2021-10-11 18:05 UTC, dusktreader commented on backend/lm_backend/api/config.py
> +async def get_config_id(product_feature: str):
Also a docstring here.

2021-10-11 18:05 UTC, dusktreader commented on agent/lm_agent/backend_utils.py
> +async def get_config_id_from_backend(product_feature: str) -> int:
Need a docstring here.

2021-10-11 23:10 UTC, dusktreader approved these changes
Nice work!

2021-10-12 02:20 UTC, jamesbeedy commented on backend/lm_backend/api/config.py
> +        ConfigurationItem(**item.dict(exclude={"features"}), features=literal_eval(item.features))
👍

2021-10-12 02:21 UTC, jamesbeedy commented on backend/lm_backend/api/config.py
> +        **config_row.dict(exclude={"features"}), features=literal_eval(config_row.features)
👍

2021-10-12 02:21 UTC, jamesbeedy commented on backend/lm_backend/api_schemas.py
> +    features: dict
👍

2021-10-12 02:21 UTC, jamesbeedy commented on backend/lm_backend/table_schemas.py
> +    Column("features", String),
👍

2021-10-12 02:22 UTC, jamesbeedy approved these changes
👍

2021-10-13 13:41 UTC, merged