Remove fastapi from agent
omnivector-solutions/license-manager pull request #67
Opened 2021-10-22 14:57 UTC by zsinx6

#### What
The agent is now just a script.

#### Why
To avoid an unnecessary fastapi running server.

https://app.clickup.com/t/1r4rmac

2021-10-22 16:10 UTC, heitorPB commented on agent/pyproject.toml
> +reconcile = "lm_agent.reconcile:main"
:+1:

2021-10-22 16:48 UTC, dusktreader requested changes
Nice Work (and quickly done)! Left a few comments for you

2021-10-22 16:48 UTC, dusktreader commented on agent/lm_agent/backend_utils.py
> +    if resp.status_code != 200:
We should still use named constants. The httpx package has them. Like `httpx.codes.OK`. There are several other places throughout the code this should apply to as well.

2021-10-22 16:48 UTC, dusktreader commented on agent/lm_agent/reconcile.py
> +    asyncio.run(run_reconcile())
What is the benefit of running this asynchronously?

2021-10-22 16:48 UTC, dusktreader commented on agent/lm_agent/reconcile.py
> +    begin_logging()
Shouldn't this go before the `backend_version_check`? There are log lines in that method.

2021-10-22 16:48 UTC, dusktreader commented on agent/lm_agent/workload_managers/slurm/cmd_utils.py
> +from lm_agent.forward import async_client
Should we just move `async_client` to this module since we removed the other forwarding logic?

2021-10-22 16:48 UTC, dusktreader commented on agent/lm_agent/workload_managers/slurm/slurmctld_epilog.py
> +    resp = await async_client().delete(f"api/v1/booking/book/{job_id}")
It seems like this logic should also be moved to the `cmd_utils` module.

2021-10-22 16:48 UTC, dusktreader commented on agent/lm_agent/reconciliation.py
> +        raise LicenseManagerBackendConnectionError()
I think it would be useful for a message to be added to this exception that describes the action that failed.

2021-10-22 16:48 UTC, dusktreader commented on agent/tests/test_reconciliation.py
> +    with pytest.raises(LicenseManagerBackendConnectionError):
If a message is added (as suggested above), it would be good to use the `match` keyword here to make sure the exception is coming from the expected place.

2021-10-22 16:51 UTC, heitorPB commented on agent/lm_agent/backend_utils.py
> +    if resp.status_code != 200:
> We should still use named constants.

Why? I prefer using numbers, as it is explicit to what it means and is also shorter.

2021-10-22 17:00 UTC, zsinx6 commented on agent/lm_agent/backend_utils.py
> +    if resp.status_code != 200:
Yeah, like there is the https://docs.python.org/3/library/http.html#http.HTTPStatus natively, but I choose to use the numbers, if it had the same format as fastapi (with the number + the name) I would switch

2021-10-22 17:01 UTC, zsinx6 commented on agent/lm_agent/reconcile.py
> +    asyncio.run(run_reconcile())
Nothing, but we need to make async calls inside the function, and it would take a lot more time to change everything to be sync

2021-10-22 17:01 UTC, zsinx6 commented on agent/lm_agent/reconcile.py
> +    begin_logging()
Totally, will fix

2021-10-22 17:02 UTC, zsinx6 commented on agent/lm_agent/reconciliation.py
> +        raise LicenseManagerBackendConnectionError()
The log above already gives all information necessary

2021-10-22 17:10 UTC, zsinx6 commented on agent/lm_agent/workload_managers/slurm/cmd_utils.py
> +from lm_agent.forward import async_client
Maybe move it to backend_utils then, but for now I think we can move with the way it is, and just make sure it is really working together with the charm

2021-10-22 18:12 UTC, jamesbeedy commented
+1 once this is tested. Nice work!

2021-10-22 21:36 UTC, dusktreader approved these changes

2021-10-25 12:41 UTC, heitorPB approved these changes

2021-10-25 16:47 UTC, merged