Add Dockerfile and docker-compose.yaml
omnivector-solutions/license-manager pull request #68
Opened 2021-10-28 13:28 UTC by julianaklulo

#### What
Add Dockerfile and docker-compose to build the application and the database.

#### Why
The project didn't have a way to run the application using containers.

2021-10-28 13:28 UTC, zsinx6 approved these changes

2021-10-28 14:28 UTC, heitorPB requested changes
Could you add some notes to the README (or somewhere else) about these?

2021-11-01 13:41 UTC, heitorPB commented on backend/Dockerfile
> +RUN apt-get install -y --fix-missing build-essential cmake libpq-dev
Why these dependencies are necessary?

2021-11-01 13:42 UTC, zsinx6 commented on backend/Dockerfile
> +RUN apt-get install -y --fix-missing build-essential cmake libpq-dev
postgres

2021-11-01 13:51 UTC, heitorPB commented on backend/Dockerfile
> +RUN apt-get install -y --fix-missing build-essential cmake libpq-dev
But we are not building the postgres image here.

The lm app starts with a clean `python:3.8` image, right (see line 18 below)? Shouldn't these deps be there instead?

2021-11-01 14:36 UTC, zsinx6 commented on backend/Dockerfile
> +RUN apt-get install -y --fix-missing build-essential cmake libpq-dev
Totally

2021-11-02 17:41 UTC, julianaklulo commented on backend/Dockerfile
> +RUN apt-get install -y --fix-missing build-essential cmake libpq-dev
I moved the postgres dependencies to the LM image.

2021-11-02 18:09 UTC, julianaklulo commented
> Could you add some notes to the README (or somewhere else) about these?

@heitorPB the README seems to be outdated, but I'll include the command to run the backend using `docker-compose`.

2021-11-03 04:23 UTC, dusktreader commented
> > Could you add some notes to the README (or somewhere else) about these?
> 
> @heitorPB the README seems to be outdated, but I'll include the command to run the backend using `docker-compose`.

There's a task to update the README as a part of the V3 deliverables: https://app.clickup.com/t/18022949/LM-43.

Adding some info about the docker-compose is fine for now, and we'll circle back to updating the README after V2.1 is finished.

2021-11-03 12:40 UTC, julianaklulo commented on backend/Dockerfile
> +RUN apt-get install -y --fix-missing build-essential cmake libpq-dev
Actually, we don't need these dependencies, I removed them and it worked.

2021-11-03 12:41 UTC, heitorPB commented on backend/Dockerfile
> +RUN pip install .
Do we need two `pip install` commands?

2021-11-03 12:46 UTC, julianaklulo commented on backend/Dockerfile
> +RUN pip install .
The `pip install .` is needed for this: https://github.com/omnivector-solutions/license-manager/blob/9a3ec291d74233550c39a28f41838a74e9c88dc3/backend/lm_backend/main.py#L62

2021-11-03 12:57 UTC, merged