Use RLM parser
omnivector-solutions/license-manager pull request #70
Opened 2021-11-04 19:22 UTC by julianaklulo

#### What
Add support for using the RLM parser.

#### Why
We need to support RLM license server.

`Task`: https://app.clickup.com/t/18022949/LM-128

2021-11-04 19:29 UTC, heitorPB commented on agent/lm_agent/tokenstat.py
> +            logger.warning(output)
Could you make these logs a bit more informative?

A return code different than zero here does not mean error?

2021-11-04 19:31 UTC, zsinx6 commented on agent/lm_agent/tokenstat.py
> +            logger.warning(output)
We just log all information we have (returncode + full cmd output), in the next line we already raise an error

2021-11-04 19:45 UTC, heitorPB commented on agent/lm_agent/tokenstat.py
> +            logger.warning(output)
If I see a log message `rc = 7` I'd  be "wtf is this? But fine, it is not an error, just a warning"

2021-11-04 21:06 UTC, dusktreader requested changes

2021-11-04 21:06 UTC, dusktreader commented on agent/lm_agent/tokenstat.py
> +            logger.warning(output)
I think we should actually include the output and the return code in a single log message. That way, they show up together in log aggregators like Graylog.

2021-11-04 21:06 UTC, dusktreader commented on agent/lm_agent/tokenstat.py
> +            logger.warning(f"rc = {proc.returncode}!")
If we are raising an exception, why are the log levels not ERROR?

2021-11-04 21:06 UTC, dusktreader commented on agent/tests/test_tokenstat.py
> +        path=Path(f"{MOCK_BIN_PATH}/rlmstat"),
`MOCK_BIN_PATH` is already a `Path`. You can just use the `/` operator:
```
path=MOCK_BIN_PATH / "rlmstat"
```

2021-11-05 14:34 UTC, julianaklulo commented on agent/lm_agent/tokenstat.py
> +            logger.warning(f"rc = {proc.returncode}!")
I changed it to error.

2021-11-05 14:35 UTC, julianaklulo commented on agent/lm_agent/tokenstat.py
> +            logger.warning(output)
I changed it to show both the output and the return code in the same log message (with level error).

2021-11-05 15:17 UTC, heitorPB commented on agent/lm_agent/tokenstat.py
> +            return feature
This returns the first occurrence of the current feature. We will never have 2 (or more) products in the parsed_list?

2021-11-05 15:33 UTC, jamesbeedy commented on agent/lm_agent/tokenstat.py
> +            return feature
I'm a little bit confused about this function too ... why are we evaluating this `feature["feature"] == product`?

Possibly it would help to add some clarification in the docstring about what the input arguments should look like or what they should contain and also what the function does with them.

2021-11-05 15:59 UTC, dusktreader approved these changes
Nice work!

2021-11-05 17:07 UTC, zsinx6 commented on agent/lm_agent/tokenstat.py
> +            return feature
Yes, the list will always have only 1 feature where the feature is equals the `product` passed

2021-11-05 20:01 UTC, jamesbeedy approved these changes
👍

2021-11-08 13:51 UTC, merged