Added separate CHANGELOGs for agent and backend
omnivector-solutions/license-manager pull request #71
Opened 2021-11-08 22:47 UTC by dusktreader

#### What
* Gathered significant changes from git history and compiled into CHANGELOG.
* Separated changelog for agent and backend.

#### Why
The main CHANGELOG was basically empty.

####
Clickup Link: https://app.clickup.com/t/18022949/LM-123

---

#### Peer Review
Please follow the upstream omnivector documentation concerning
[peer-review guidelines](https://github.com/omnivector-solutions/Documentation/blob/main/Contributing/pr_review_standards.md#peer-review).

2021-11-09 12:58 UTC, heitorPB commented on backend/CHANGELOG.rst
> +* Agent:
```suggestion
* Backend:

  * Added alembic support
  * Added bookings endpoints
  * Added FastAPI app for backend
  
* Agent:

```

rst needs empty lines around nested list items.

2021-11-09 12:59 UTC, heitorPB requested changes
Missing empty lines after the section names and around subitems in lists

2021-11-09 18:15 UTC, dusktreader commented on backend/CHANGELOG.rst
> +* Agent:
Addressed in latest commit.

2021-11-09 18:18 UTC, jamesbeedy approved these changes
👍

2021-11-17 20:59 UTC, julianaklulo requested changes
Spotted a few typos

2021-11-17 20:59 UTC, julianaklulo commented on agent/CHANGELOG.rst
> +* Converted agent to a CLI application (from FastAPI with intenral scheduler)
```suggestion
* Converted agent to a CLI application (from FastAPI with internal scheduler)
```

2021-11-17 20:59 UTC, julianaklulo commented on agent/CHANGELOG.rst
> +  * Skip eplilog cleanup loop if there are no bookings
```suggestion
  * Skip epilog cleanup loop if there are no bookings
```

2021-11-17 20:59 UTC, julianaklulo commented on agent/CHANGELOG.rst
> +  * Added forced reconcilliation to the prolog
```suggestion
  * Added forced reconciliation to the prolog
```

2021-11-17 20:59 UTC, julianaklulo commented on backend/CHANGELOG.rst
> +  * Skip eplilog cleanup loop if there are no bookings
```suggestion
  * Skip epilog cleanup loop if there are no bookings
```

2021-11-17 20:59 UTC, julianaklulo commented on backend/CHANGELOG.rst
> +  * Added forced reconcilliation to the prolog
```suggestion
  * Added forced reconciliation to the prolog
```

2021-11-18 18:41 UTC, dusktreader commented on agent/CHANGELOG.rst
> +* Converted agent to a CLI application (from FastAPI with intenral scheduler)
Will be updated in next commit.

2021-11-18 18:41 UTC, dusktreader commented on agent/CHANGELOG.rst
> +  * Skip eplilog cleanup loop if there are no bookings
Will be updated in next commit.

2021-11-18 18:41 UTC, dusktreader commented on agent/CHANGELOG.rst
> +  * Added forced reconcilliation to the prolog
Will be updated in next commit.

2021-11-18 18:42 UTC, dusktreader commented on backend/CHANGELOG.rst
> +  * Skip eplilog cleanup loop if there are no bookings
Will be updated in next commit.

2021-11-18 18:42 UTC, dusktreader commented on backend/CHANGELOG.rst
> +  * Added forced reconcilliation to the prolog
Will be updated in next commit.

2021-11-18 19:02 UTC, julianaklulo approved these changes

2021-11-18 19:23 UTC, heitorPB approved these changes

2021-11-18 21:42 UTC, merged