LM-119 Added security via Armasec
omnivector-solutions/license-manager pull request #78
Opened 2021-12-01 18:25 UTC by dusktreader

#### What
This adds authorization on a route-to-route basis via Armasec.

#### Why
This is key to moving License Manager to k8s. Next, we will remove the jawthorizer.

`Task`: https://app.clickup.com/t/18022949/LM-119
---

#### Peer Review
Please follow the upstream omnivector documentation concerning
[peer-review guidelines](https://github.com/omnivector-solutions/Documentation/blob/main/Contributing/pr_review_standards.md#peer-review).

2021-12-01 18:37 UTC, heitorPB commented on agent/pyproject.toml
> +ipython = "^7.30.0"
why `ipython` is here? Is it really necessary?

2021-12-01 23:37 UTC, jamesbeedy commented on backend/lm_backend/api/license.py
> +    dependencies=[Depends(guard.lockdown("license-manager:in-use:read"))],
`s/in-use/license/g`

2021-12-02 15:01 UTC, matheushent requested changes
The convention for the permission name is quite different from the Admin API. I think we should stardardize it. My suggestion is:

`<operation>:<application>:<target>`

e.g. `write:license-manager:config`, `read:license-manager:config`

2021-12-02 18:05 UTC, dusktreader commented
> The convention for the permission name is quite different from the Admin API. I think we should stardardize it. My suggestion is:
> 
> `<operation>:<application>:<target>`
> 
> e.g. `write:license-manager:config`, `read:license-manager:config`

It agrees with the permissions set up in Jobbergate:
`<application>:<target>:<operation>`

2021-12-02 18:05 UTC, dusktreader commented on agent/pyproject.toml
> +ipython = "^7.30.0"
It's just added here as a dev dependency because I use it for deugging/testing. I can remove it, but it won't affect production builds.

2021-12-02 18:06 UTC, dusktreader commented on agent/pyproject.toml
> +ipython = "^7.30.0"
Removed in latest commit.

2021-12-02 18:09 UTC, dusktreader commented on backend/lm_backend/api/license.py
> +    dependencies=[Depends(guard.lockdown("license-manager:in-use:read"))],
Changed in latest commit.

2021-12-02 18:42 UTC, julianaklulo requested changes
This is looking good!
Found one test with an odd name though.

2021-12-02 18:42 UTC, julianaklulo commented on backend/tests/api/test_config.py
> +async def test_delete_configuration__success(
The name of this test is the same as the test above, it should be
```suggestion
async def test_delete_configuration__fail_on_bad_permission(
```

2021-12-02 19:42 UTC, dusktreader commented on backend/tests/api/test_config.py
> +async def test_delete_configuration__success(
Oooh, good catch! There was a lot of copy-pasta being thrown around! Not surprised some of it stuck to the wall.

2021-12-02 19:44 UTC, dusktreader commented on backend/tests/api/test_config.py
> +async def test_delete_configuration__success(
Fixed in latest commit.

2021-12-02 22:59 UTC, jamesbeedy approved these changes
Sweet!!!!! 👍

2021-12-02 23:15 UTC, merged