LM-144 Added machine-to-machine auth for license-manager-agent
omnivector-solutions/license-manager pull request #79
Opened 2021-12-02 01:44 UTC by dusktreader

#### What
Added support for machine-to-machine auth via Auth0 and armasec to the agent

#### Why
With the backend using armasec for token security, it is necessary to update the agent so it can consume the backend with the new security scheme.

`Task`: https://app.clickup.com/t/18022949/LM-144

---

#### Peer Review
Please follow the upstream omnivector documentation concerning
[peer-review guidelines](https://github.com/omnivector-solutions/Documentation/blob/main/Contributing/pr_review_standards.md#peer-review).

2021-12-02 15:04 UTC, matheushent commented on agent/lm_agent/backend_utils.py
> +    return token
as far as I could understand, this token is capable of calling the management API and change stuff there. This is dangerous. Is there another way to do it?

2021-12-02 18:02 UTC, dusktreader commented on agent/lm_agent/backend_utils.py
> +    return token
This app is only give access to the regular Auth0 api that standard user tokens have access to as well. That's controlled in Auth0

2021-12-02 18:03 UTC, dusktreader commented on agent/lm_agent/backend_utils.py
> +    return token
See: 
![image](https://user-images.githubusercontent.com/713676/144478144-82aecf8f-f699-4bcc-b7ff-c9ab7a2d5376.png)

2021-12-02 18:04 UTC, matheushent commented on agent/lm_agent/backend_utils.py
> +    return token
ohhhh I see. Thanks for explaining

2021-12-02 19:32 UTC, julianaklulo commented on agent/bin/lmconfigure.py
> -        ctxt['features'] = features.split(",")
Why is this not needed anymore?

2021-12-02 19:32 UTC, julianaklulo commented on agent/tests/test_backend_utils.py
> +                # Another valid conig row
```suggestion
                # Another valid config row
```

2021-12-02 19:32 UTC, julianaklulo commented on backend/docker-compose.yaml
> +      dockerfile: ./Dockerfile-dev
Why do we need a new Dockerfile? And what is the volume being used for?

2021-12-02 21:53 UTC, dusktreader commented on agent/bin/lmconfigure.py
> -        ctxt['features'] = features.split(",")
I don't think it was working in the first place. The backend's config endpoint and table both expect the "features" field to be a string. Splitting it was resulting in a 422 from the backend.

2021-12-02 21:56 UTC, dusktreader commented on backend/docker-compose.yaml
> +      dockerfile: ./Dockerfile-dev
The dev dockerfile allows us to volume mount the source code so that we can have the uvicorn server restart when one of the files is changed. This way, you don't have to bring down your docker images and spin them back up every time you make a code change.

2021-12-02 22:04 UTC, dusktreader commented on agent/tests/test_backend_utils.py
> +                # Another valid conig row
Fixed in latest commit.

2021-12-02 22:43 UTC, jamesbeedy commented on agent/pyproject.toml
>  lm-create-jwt = "bin.createjwt:main"
please remove this and the associated code - thx

2021-12-02 22:46 UTC, jamesbeedy commented on backend/lm_backend/api/config.py
> +        # It is necessary to exclude None so the database won't attempt to insert a null id
👍

2021-12-02 22:48 UTC, jamesbeedy commented on agent/lm_agent/backend_utils.py
> +    response = httpx.post(auth0_url, data=auth0_body)
can we cache the token here and only refresh or regenerate if it is expired?

2021-12-02 22:52 UTC, jamesbeedy requested changes
Nice work!

2021-12-03 01:21 UTC, dusktreader commented on agent/pyproject.toml
>  lm-create-jwt = "bin.createjwt:main"
Removed in latest commit.

2021-12-03 01:21 UTC, dusktreader commented on agent/lm_agent/backend_utils.py
> +    response = httpx.post(auth0_url, data=auth0_body)
Caching added in latest commit (and a bunch of unit tests).

2021-12-03 13:57 UTC, julianaklulo commented on backend/docker-compose.yaml
> +      dockerfile: ./Dockerfile-dev
Nice, thanks for the explanation!

2021-12-03 18:26 UTC, julianaklulo approved these changes
Nice work with the token cache!

2021-12-03 18:28 UTC, merged