Docs init
omnivector-solutions/license-manager pull request #89
Opened 2021-12-14 16:15 UTC by jamesbeedy

#### What
Start writing the development documentation for the license-manager.

#### Why
We need docs!

2021-12-14 16:30 UTC, heitorPB commented on docs-source/architecture.rst
> +The `lm_agent` is responsible for keeping the local cluster license totals
```suggestion
The ``lm_agent`` is responsible for keeping the local cluster license totals
```

rst uses double backticks for inline code.

2021-12-14 16:31 UTC, heitorPB commented on docs-source/architecture.rst
> +and updates the license-manager backend on a periodic basis referred to as the `stat-interval`.
```suggestion
and updates the license-manager backend on a periodic basis referred to as the ``stat-interval``.
```

2021-12-14 16:32 UTC, heitorPB commented on docs-source/architecture.rst
> +When slurm is configured to use the `PrologSlurmctld` provided by `lm_agent`, it will make a
```suggestion
When Slurm is configured to use the ``PrologSlurmctld`` provided by ``lm_agent``, it will make a
```

2021-12-14 16:32 UTC, heitorPB commented on docs-source/architecture.rst
> +The `PrologSlurmctld` will exit 1 if the booking cannot be made and 0 if the booking succeeds.
```suggestion
request to the license-manager backend to book license prior to the allocation of a job.
The ``PrologSlurmctld`` will exit with status ``1`` if the booking cannot be made and ``0`` if the booking succeeds.
```

2021-12-14 16:36 UTC, heitorPB commented on docs-source/architecture.rst
> +* SLURM
```suggestion
* Slurm
```

Just the S should be uppercase: https://slurm.schedmd.com/SLUG19/Welcome.pdf

2021-12-14 16:36 UTC, heitorPB commented on docs-source/architecture.rst
> +* `/config`
```suggestion
* ``/license``
* ``/booking``
* ``/config``
```

LM also has health-checks?

2021-12-14 16:37 UTC, heitorPB commented on docs-source/development.rst
> +The slurm cluster is now prepared for further configuration and use in ``licnese-manager`` development.
```suggestion
The Slurm cluster is now prepared for further configuration and use in ``license-manager`` development.
```

2021-12-14 16:39 UTC, heitorPB commented on docs-source/getting_started.rst
> +1) Slurm cluster (where `lm_agent` runs)
```suggestion
1) Slurm cluster (where ``lm_agent`` runs)
```

2021-12-14 16:39 UTC, heitorPB commented on docs-source/index.rst
> +source of truth for what licenses are actually available.
:+1:

2021-12-14 16:42 UTC, heitorPB commented on docs-source/conf.py
> +html_static_path = ['_static']
The slurm docs use the `sphinx-book-theme`, to use it (if want/need to have all our docs with the same theme):
-  set here the theme and the settings, as in https://github.com/omnivector-solutions/osd-documentation/blob/master/conf.py#L42-L48
- add `sphinx-book-theme` to the dependency list

2021-12-14 20:14 UTC, julianaklulo commented on docs-source/development.rst
> +
To finish setting license-manager-simulator, we also need to copy the template files to simulate flexlm/rlm. I feel like this fits in this additional modifications section.

2021-12-14 20:15 UTC, julianaklulo reviewed
This is looking great!

2021-12-29 19:36 UTC, dusktreader requested changes

2021-12-29 19:36 UTC, dusktreader commented on docs-source/architecture.rst
> +request to the license-manager backend to book license prior to the allocation of a job.
```suggestion
request to the license-manager backend to book the needed licenses prior to the allocation of a job.
```

2021-12-29 19:36 UTC, dusktreader commented on docs-source/development.rst
> +Development of the ``license-manager`` involves running a mix of different services in docker and LXD containers.
```suggestion
The ``license-manager`` application incorporates a mix of different services in docker and LXD containers.
```

2021-12-29 19:36 UTC, dusktreader commented on docs-source/development.rst
> +Before you get started, enusure you have the following pre-requisites installed on your machine.
```suggestion
Before you get started, enusure you have the following pre-requisites installed on your machine:
```

2021-12-29 19:36 UTC, dusktreader commented on docs-source/development.rst
> +``docker ps`` shows
```suggestion
``docker ps`` shows:
```

2021-12-29 19:36 UTC, dusktreader commented on docs-source/development.rst
> +      -H 'accept: application/json' | jq
What's the purpose of piping the output to jq. We aren't parsing it here, and `jq` isn't listed as a dependency. I think we should drop it.

2021-12-29 19:36 UTC, dusktreader commented on docs-source/development.rst
> +Following the ``make charm`` command you should be left with a resultant charm artifact named
```suggestion
The ``make charm`` command will produce a resultant charm artifact named
```

2021-12-29 19:36 UTC, dusktreader commented on docs-source/development.rst
> +We need to define a configuration file to be used with the license-manager-agent charm.
Before deploying the charm, create a YAML configuration file that contains the needed settings for the license-manager-agent charm. The config should look something like this:

2021-12-29 19:36 UTC, dusktreader commented on docs-source/development.rst
> +templated in to the file.
```suggestion
Make sure to substitute the correct values into the new ``license-manager-agent.yaml`` configuration file
(especially the ip address of your host machine)
```

2021-12-29 19:36 UTC, dusktreader commented on docs-source/development.rst
> +   EOF
```suggestion
.. code-block:: yaml

   license-manager-agent:
     log-level: DEBUG
     stat-interval: 30
     jwt-key: "your.jwt.key"
     pypi-url: "https://pypicloud.omnivector.solutions"
     pypi-username: "<pypi-username>"
     pypi-password: "<pypi-password>"
     license-manager-backend-base-url: "http://$MY_IP:7000"
     lmstat-path: "/usr/local/bin/lmstat"
     rlmstat-path: "/usr/local/bin/rlmutil"
```

2021-12-29 19:36 UTC, dusktreader commented on docs-source/development.rst
> +the config file for the charm (``license-manager-agent.yaml``), we are ready to deploy.
```suggestion
Now that we have the charm artifact (``license-manager-agent_ubuntu-20.04-amd64_centos-7-amd64.charm``) and 
the config file for the charm (``license-manager-agent.yaml``), we are ready to deploy.
```

2021-12-29 19:36 UTC, dusktreader commented on docs-source/development.rst
> +3) license-manager backend.
```suggestion
At this point you should have 3 systems running:

1. slurm cluster in LXD
2. license-manager-simulator
3. license-manager backend
```

2021-12-29 19:36 UTC, dusktreader commented on docs-source/development.rst
> +Also make sure you have the correct configurations for the agent. Some of them were already specified in the ``license-manager-agent.yaml``
```suggestion
You should also make sure you have used the correct configurations for the agent. Some of them were already specified in the ``license-manager-agent.yaml``
```

2021-12-29 19:36 UTC, dusktreader commented on docs-source/development.rst
> +the nodes of the cluster as a final step in configuring the system.
The wording here is a bit confusing. Maybe it needs to be broken up into more than one sentence.

2021-12-29 19:36 UTC, dusktreader commented on docs-source/development.rst
> +The fake application makes a request to the license-manager-simulator API to book 42 licenses, sleeps for a few seconds, and delete the booking after.
```suggestion
The fake application makes a request to the license-manager-simulator API to book 42 licenses, sleeps for a few seconds, and then deletes the booking after.
```

2021-12-29 19:36 UTC, dusktreader commented on docs-source/development.rst
> +Copy the files to the slurmd machine /tmp folder. Also modify the URL in the ``application.sh`` to reflect the ip address of the machine where the
```suggestion
Copy the files to the slurmd machine ``/tmp`` folder. Also modify the URL in the ``application.sh`` to reflect the IP address of the machine where the
```

2021-12-29 19:36 UTC, dusktreader commented on docs-source/development.rst
> +You also should have a new booking created, make a request to the ``booking`` endpoint to check.
```suggestion
You also should have a new booking created. To verify this, make a request to the ``booking`` endpoint to check.
```

2021-12-29 19:36 UTC, dusktreader commented on docs-source/getting_started.rst
> +3) license-manager-backend
```suggestion
1. Slurm cluster (where ``lm_agent`` runs)
2. License server (FlexLM, RLM, license-manager-simulator)
3. license-manager-backend
```

2021-12-29 19:36 UTC, dusktreader commented on docs-source/index.rst
> +an HPC cluster and one or more 3rd party license servers. The license-manager
```suggestion
The license-manager is a license scheduling middleware that operates as an interface between
an HPC cluster and one or more 3rd party license servers. The license-manager
```

2021-12-29 20:01 UTC, julianaklulo commented on docs-source/architecture.rst
> +request to the license-manager backend to book license prior to the allocation of a job.
Addressed in latest commit.

2021-12-29 20:02 UTC, julianaklulo commented on docs-source/development.rst
> +Development of the ``license-manager`` involves running a mix of different services in docker and LXD containers.
Addressed in latest commit.

2021-12-29 20:03 UTC, julianaklulo commented on docs-source/development.rst
> +Before you get started, enusure you have the following pre-requisites installed on your machine.
Addressed in latest commit.

2021-12-29 20:03 UTC, julianaklulo commented on docs-source/development.rst
> +``docker ps`` shows
Addressed in latest commit.

2021-12-29 20:04 UTC, julianaklulo commented on docs-source/development.rst
> +      -H 'accept: application/json' | jq
I removed it.

2021-12-29 20:05 UTC, julianaklulo commented on docs-source/development.rst
> +Following the ``make charm`` command you should be left with a resultant charm artifact named
Addressed in latest commit.

2021-12-29 20:06 UTC, julianaklulo commented on docs-source/development.rst
> +We need to define a configuration file to be used with the license-manager-agent charm.
Addressed in latest commit.

2021-12-29 20:07 UTC, julianaklulo commented on docs-source/development.rst
> +templated in to the file.
Addressed in latest commit.

2021-12-29 20:08 UTC, julianaklulo commented on docs-source/development.rst
> +   EOF
Addressed in latest commit.

2021-12-29 20:08 UTC, julianaklulo commented on docs-source/development.rst
> +the config file for the charm (``license-manager-agent.yaml``), we are ready to deploy.
Addressed in latest commit.

2021-12-29 20:09 UTC, julianaklulo commented on docs-source/development.rst
> +3) license-manager backend.
Addressed in latest commit.

2021-12-29 20:10 UTC, julianaklulo commented on docs-source/development.rst
> +Also make sure you have the correct configurations for the agent. Some of them were already specified in the ``license-manager-agent.yaml``
Addressed in latest commit.

2021-12-29 20:11 UTC, julianaklulo commented on docs-source/development.rst
> +The fake application makes a request to the license-manager-simulator API to book 42 licenses, sleeps for a few seconds, and delete the booking after.
Addressed in latest commit.

2021-12-29 20:12 UTC, julianaklulo commented on docs-source/development.rst
> +Copy the files to the slurmd machine /tmp folder. Also modify the URL in the ``application.sh`` to reflect the ip address of the machine where the
Addressed in latest commit.

2021-12-29 20:13 UTC, julianaklulo commented on docs-source/development.rst
> +You also should have a new booking created, make a request to the ``booking`` endpoint to check.
Addressed in latest commit.

2021-12-29 20:13 UTC, julianaklulo commented on docs-source/getting_started.rst
> +3) license-manager-backend
Addressed in latest commit.

2021-12-29 20:14 UTC, julianaklulo commented on docs-source/index.rst
> +an HPC cluster and one or more 3rd party license servers. The license-manager
Addressed in latest commit.

2021-12-29 20:21 UTC, julianaklulo commented on docs-source/development.rst
> +the nodes of the cluster as a final step in configuring the system.
```suggestion
These configurations will ensure that your slurm cluster has a fake license server client and available licenses to be used by the fake application, which will be run as a batch script.
```
Is this better?

2021-12-29 20:59 UTC, dusktreader approved these changes

2021-12-29 21:02 UTC, merged